<a href="https://colab.research.google.com/github/morty649/morty649/blob/main/nb/Qwen3_(4B)-GRPO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your local device, follow [our guide](https://unsloth.ai/docs/get-started/install). This notebook is licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & how to save it

### News

Train MoEs - DeepSeek, GLM, Qwen and gpt-oss 12x faster with 35% less VRAM. [Blog](https://unsloth.ai/docs/new/faster-moe)

You can now train embedding models 1.8-3.3x faster with 20% less VRAM. [Blog](https://unsloth.ai/docs/new/embedding-finetuning)

Ultra Long-Context Reinforcement Learning is here with 7x more context windows! [Blog](https://unsloth.ai/docs/new/grpo-long-context)

3x faster LLM training with 30% less VRAM and 500K context. [3x faster](https://unsloth.ai/docs/new/3x-faster-training-packing) • [500K Context](https://unsloth.ai/docs/new/500k-context-length-fine-tuning)

New in Reinforcement Learning: [FP8 RL](https://unsloth.ai/docs/new/fp8-reinforcement-learning) • [Vision RL](https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl) • [Standby](https://unsloth.ai/docs/basics/memory-efficient-rl) • [gpt-oss RL](https://unsloth.ai/docs/new/gpt-oss-reinforcement-learning)

Visit our docs for all our [model uploads](https://unsloth.ai/docs/get-started/unsloth-model-catalog) and [notebooks](https://unsloth.ai/docs/get-started/unsloth-notebooks).

### Installation

In [1]:
%%capture
import os
os.environ["UNSLOTH_VLLM_STANDBY"] = "1" # [NEW] Extra 30% context lengths!
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install or uv pip install
    !pip install unsloth vllm
else:
    pass # For Colab / Kaggle, we need extra instructions hidden below \/

In [2]:
#@title Colab Extra Install { display-mode: "form" }
%%capture
import os
!pip install --upgrade -qqq uv
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install!
    !pip install unsloth vllm
else:
    try: import numpy, PIL; _numpy = f'numpy=={numpy.__version__}'; _pil = f'pillow=={PIL.__version__}'
    except: _numpy = "numpy"; _pil = "pillow"
    try: import subprocess; is_t4 = "Tesla T4" in str(subprocess.check_output(["nvidia-smi"]))
    except: is_t4 = False
    _vllm, _triton = ('vllm==0.9.2', 'triton==3.2.0') if is_t4 else ('vllm==0.15.1', 'triton')
    !uv pip install -qqq --upgrade {_vllm} {_numpy} {_pil} torchvision bitsandbytes xformers unsloth
    !uv pip install -qqq {_triton}
!uv pip install transformers==4.56.2
!uv pip install --no-deps trl==0.22.2

### Unsloth

Goal: To convert `Qwen3-4B-Base` into a reasoning model via GRPO by using OpenR1's Math dataset.

We first pre fine-tune the model to make GRPO skip trying to match formatting - this speeds GRPO up.

In [3]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # Can increase for longer reasoning traces
lora_rank = 32 # Larger rank = smarter, but slower

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Qwen3-4B-Base",
    max_seq_length = max_seq_length,
    load_in_4bit = False, # False for LoRA 16bit
    fast_inference = True, # Enable vllm fast inference
    max_lora_rank = lora_rank,
    gpu_memory_utilization = 0.9, # Reduce if out of memory
)

model = FastLanguageModel.get_peft_model(
    model,
    r = lora_rank, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha = lora_rank*2, # *2 speeds up training
    use_gradient_checkpointing = "unsloth", # Reduces memory usage
    random_state = 3407,
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 03-08 05:17:32 [__init__.py:244] Automatically detected platform cuda.
ERROR 03-08 05:17:39 [fa_utils.py:57] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
🦥 Unsloth Zoo will now patch everything to make training faster!
INFO 03-08 05:17:50 [vllm_utils.py:723] Unsloth: Patching vLLM v1 graph capture
INFO 03-08 05:17:50 [vllm_utils.py:752] Unsloth: Patching vLLM v0 graph capture
==((====))==  Unsloth 2026.3.3: Fast Qwen3 patching. Transformers: 4.56.2. vLLM: 0.9.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.30. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Standby mode is enabled. However your setting of `gpu_memory_utilization` will OOM.
Changing `gpu_memory_utilization` to 0.8.
Unsloth: vLLM loading unsloth/Qwen3-4B-Base with actual GPU utilization = 79.22%
Unsloth: Your GPU has CUDA compute capability 7.5 with VRAM = 14.56 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 2048. Num Sequences = 32.
Unsloth: vLLM's KV Cache can use up to 4.44 GB. Also swap space = 0 GB.
Unsloth: `cudagraph_mode` is not in `from vllm.config import CompilationConfig`
Unsloth: Disabling `disable_cascade_attn` in vLLM to allow for better on policy RL!
INFO 03-08 05:18:19 [config.py:841] This model supports multiple tasks: {'embed', 'reward', 'generate', 'classify'}. Defaulting to 'generate'.

`torch_dtype` is deprecated! Use `dtype` instead!

WARNING 03-08 05:18:19 [config.py:3371] Casting torch.bfloat16 to torch.float16.
INFO 03-08 05:18:19 [config.py:1472] Using max model len 2048
WARNING 03-08 05:18:19 [arg_utils.py:1735] Compute Capability < 8.0 is not supported by the V1 Engine. Falling back to V0.
INFO 03-08 05:18:20 [config.py:2285] Chunked prefill is enabled with max_num_batched_tokens=4096.
INFO 03-08 05:18:20 [llm_engine.py:230] Initializing a V0 LLM engine (v0.9.2) with config: model='unsloth/Qwen3-4B-Base', speculative_config=None, tokenizer='unsloth/Qwen3-4B-Base', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen3-4B-Base, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"inductor","custom_ops":[],"splitting_ops":[],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"epilogue_fusion":true,"max_autotune":false,"shape_padding":true,"trace.enabled":false,"triton.cudagraphs":true,"debug":false,"dce":true,"memory_planning":true,"coordinate_descent_tuning":false,"trace.graph_diagram":false,"compile_threads":4,"group_fusion":true,"disable_progress":false,"verbose_progress":true,"triton.multi_kernel":0,"triton.use_block_ptr":true,"triton.enable_persistent_tma_matmul":true,"triton.autotune_at_compile_time":false,"triton.cooperative_reductions":false,"cuda.compile_opt_level":"-O2","cuda.enable_cuda_lto":true,"combo_kernels":false,"benchmark_combo_kernel":true,"combo_kernel_foreach_dynamic_shapes":true,"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":true,"max_capture_size":32,"local_cache_dir":null}, use_cached_outputs=False,

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/617 [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/166 [00:00<?, ?B/s]

INFO 03-08 05:18:22 [cuda.py:311] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 03-08 05:18:22 [cuda.py:360] Using XFormers backend.
INFO 03-08 05:18:23 [parallel_state.py:1076] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
INFO 03-08 05:18:23 [model_runner.py:1171] Starting to load model unsloth/Qwen3-4B-Base...
INFO 03-08 05:18:24 [weight_utils.py:292] Using model weights format ['*.safetensors']

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.08G [00:00<?, ?B/s]

INFO 03-08 05:19:39 [weight_utils.py:308] Time spent downloading weights for unsloth/Qwen3-4B-Base: 75.255417 seconds

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]

INFO 03-08 05:20:21 [default_loader.py:272] Loading weights took 41.29 seconds
INFO 03-08 05:20:21 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 03-08 05:20:24 [model_runner.py:1203] Model loading took 7.6765 GiB and 117.388797 seconds
INFO 03-08 05:20:39 [worker.py:294] Memory profiling takes 12.34 seconds
INFO 03-08 05:20:39 [worker.py:294] the current vLLM instance can use total_gpu_memory (14.56GiB) x gpu_memory_utilization (0.79) = 11.54GiB
INFO 03-08 05:20:39 [worker.py:294] model weights take 7.68GiB; non_torch_memory takes 0.03GiB; PyTorch activation peak memory takes 0.31GiB; the rest of the memory reserved for KV Cache is 3.52GiB.
INFO 03-08 05:20:40 [executor_base.py:113] # cuda blocks: 1602, # CPU blocks: 0
INFO 03-08 05:20:40 [executor_base.py:118] Maximum concurrency for 2048 tokens per request: 12.52x
INFO 03-08 05:20:40 [vllm_utils.py:757] Unsloth: Running patched vLLM v0 `capture_model`.
INFO 03-08 05:20:40 [model_runner.py:1513] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.

Capturing CUDA graph shapes:   0%|          | 0/7 [00:00<?, ?it/s]

INFO 03-08 05:21:07 [model_runner.py:1671] Graph capturing finished in 27 secs, took 0.10 GiB
INFO 03-08 05:21:07 [vllm_utils.py:764] Unsloth: Patched vLLM v0 graph capture finished in 27 secs.
INFO 03-08 05:21:10 [llm_engine.py:428] init engine (profile, create kv cache, warmup model) took 45.98 seconds
Unsloth: Just some info: will skip parsing ['ffn_norm', 'norm1', 'norm', 'post_attention_layernorm', 'norm2', 'post_layernorm', 'k_norm', 'layer_norm2', 'post_feedforward_layernorm', 'pre_feedforward_layernorm', 'layer_norm1', 'input_layernorm', 'attention_norm', 'q_norm']

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of Qwen3ForCausalLM were not initialized from the model checkpoint at unsloth/Qwen3-4B-Base and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Performing substitution for additional_keys=set()
Unsloth: Just some info: will skip parsing ['ffn_norm', 'norm1', 'norm', 'post_attention_layernorm', 'norm2', 'cross_attn_post_attention_layernorm', 'post_layernorm', 'k_norm', 'layer_norm2', 'post_feedforward_layernorm', 'pre_feedforward_layernorm', 'layer_norm1', 'cross_attn_input_layernorm', 'input_layernorm', 'attention_norm', 'q_norm']

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/617 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

unsloth/Qwen3-4B-Base does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.

Unsloth 2026.3.3 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

### GRPO chat template
Since we're using a base model, we should set a chat template. You can make your own chat template as well!
1. DeepSeek uses `<think>` and `</think>`, but this is **not** necessary - you can customize it however you like!
2. A `system_prompt` is recommended to at least guide the model's responses.

In [4]:
reasoning_start = "<brain>" # Acts as <think>
reasoning_end   = "</brain>"   # Acts as </think>
solution_start  = "<answer>"
solution_end    = "</answer>"

system_prompt = \
f"""You are given a problem.
Think about the problem and provide your working out.
Place it between {reasoning_start} and {reasoning_end}.
Then, provide your solution between {solution_start}{solution_end}"""
system_prompt

'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <brain> and </brain>.\nThen, provide your solution between <answer></answer>'

We create a simple chat template below. Notice `add_generation_prompt` includes prepending `<start_working_out>` to guide the model to start its reasoning process.

In [5]:
chat_template = \
    "{% if messages[0]['role'] == 'system' %}"\
        "{{ messages[0]['content'] + eos_token }}"\
        "{% set loop_messages = messages[1:] %}"\
    "{% else %}"\
        "{{ '{system_prompt}' + eos_token }}"\
        "{% set loop_messages = messages %}"\
    "{% endif %}"\
    "{% for message in loop_messages %}"\
        "{% if message['role'] == 'user' %}"\
            "{{ message['content'] }}"\
        "{% elif message['role'] == 'assistant' %}"\
            "{{ message['content'] + eos_token }}"\
        "{% endif %}"\
    "{% endfor %}"\
    "{% if add_generation_prompt %}{{ '{reasoning_start}' }}"\
    "{% endif %}"

# Replace with our specific template:
chat_template = chat_template\
    .replace("'{system_prompt}'",   f"'{system_prompt}'")\
    .replace("'{reasoning_start}'", f"'{reasoning_start}'")
tokenizer.chat_template = chat_template

Let's see how our chat template behaves on an example:

In [6]:
tokenizer.apply_chat_template([
    {"role" : "user", "content" : "What is 1+1?"},
    {"role" : "assistant", "content" : f"{reasoning_start}I think it's 2.{reasoning_end}{solution_start}2{solution_end}"},
    {"role" : "user", "content" : "What is 2+2?"},
], tokenize = False, add_generation_prompt = True)

"You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <brain> and </brain>.\nThen, provide your solution between <answer></answer><|endoftext|>What is 1+1?<brain>I think it's 2.</brain><answer>2</answer><|endoftext|>What is 2+2?<brain>"

### Pre fine-tuning for formatting
We now use a subset of NVIDIA's [Open Math Reasoning dataset](https://huggingface.co/datasets/nvidia/OpenMathReasoning) which was filtered to only include high quality DeepSeek R1 traces.

We'll only filter ~59 or so examples to first "prime" / pre fine-tune the model to understand our custom GRPO formatting.

In [7]:
from datasets import load_dataset
import pandas as pd
import numpy as np

dataset = load_dataset("unsloth/OpenMathReasoning-mini", split = "cot")
dataset = dataset.to_pandas()[
    ["expected_answer", "problem", "generated_solution"]
]

# Try converting to number - if not, replace with NaN
is_number = pd.to_numeric(pd.Series(dataset["expected_answer"]), errors = "coerce").notnull()
# Select only numbers
dataset = dataset.iloc[np.where(is_number)[0]]

dataset

README.md:   0%|          | 0.00/603 [00:00<?, ?B/s]

data/cot-00000-of-00001.parquet:   0%|          | 0.00/106M [00:00<?, ?B/s]

Generating cot split:   0%|          | 0/19252 [00:00<?, ? examples/s]

,expected_answer,problem,generated_solution
0,14,Given $\sqrt{x^2+165}-\sqrt{x^2-52}=7$ and $x$...,"<think>\nOkay, let's see. I need to solve the ..."
6,-2,Find the value of the parameter $a$ for which ...,"<think>\nOkay, so I need to find the value of ..."
9,18,What is the sum of all real numbers $x$ for wh...,"<think>\nOkay, so I need to solve the equation..."
13,2,Evaluate the sum \(\sum_{n=1}^\infty \frac{\ph...,"<think>\nOkay, so I need to evaluate the infin..."
17,30,What is the largest positive integer that divi...,"<think>\nAlright, so I need to find the larges..."
...,...,...,...
19243,244,"Let \( p \), \( q \), and \( r \) be the disti...","<think>\nOkay, so I need to find the value of ..."
19245,1,A bug is on the $0$ of a number line. At any p...,"<think>\nOkay, so I have this problem where a ..."
19247,4,A bus left point X for point Y. Two hours late...,"<think>\nOkay, let's tackle this problem step ..."
19248,18,Each interior angle of a regular n-gon measure...,"<think>\nOkay, let's see. I need to find the n..."
19250,0.8960,Find the probability that the second blue resu...,"<think>\nOkay, so I need to find the probabili..."

We have to format the dataset to follow our GRPO style formatting:

In [8]:
def format_dataset(x):
    expected_answer = x["expected_answer"]
    problem = x["problem"]

    # Remove generated <think> and </think>
    thoughts = x["generated_solution"]
    thoughts = thoughts.replace("<think>", "").replace("</think>", "")

    # Strip newlines on left and right
    thoughts = thoughts.strip()
    # Add our custom formatting
    final_prompt = \
        reasoning_start + thoughts + reasoning_end + \
        solution_start + expected_answer + solution_end
    return [
        {"role" : "system",    "content" : system_prompt},
        {"role" : "user",      "content" : problem},
        {"role" : "assistant", "content" : final_prompt},
    ]

dataset["Messages"] = dataset.apply(format_dataset, axis = 1)

Check to see if it worked:

In [9]:
tokenizer.apply_chat_template(dataset["Messages"][0], tokenize = False)

"You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <brain> and </brain>.\nThen, provide your solution between <answer></answer><|endoftext|>Given $\\sqrt{x^2+165}-\\sqrt{x^2-52}=7$ and $x$ is positive, find all possible values of $x$.<brain>Okay, let's see. I need to solve the equation √(x² + 165) - √(x² - 52) = 7, and find all positive values of x. Hmm, radicals can be tricky, but maybe if I can eliminate the square roots by squaring both sides. Let me try that.\n\nFirst, let me write down the equation again to make sure I have it right:\n\n√(x² + 165) - √(x² - 52) = 7.\n\nOkay, so the idea is to isolate one of the radicals and then square both sides. Let me try moving the second radical to the other side:\n\n√(x² + 165) = 7 + √(x² - 52).\n\nNow, if I square both sides, maybe I can get rid of the square roots. Let's do that:\n\n(√(x² + 165))² = (7 + √(x² - 52))².\n\nSimplifying the left side:\n\nx² + 165 = 49 + 14√(x² - 52) + (√(x² - 52))².\n\nThe right side is expanded using the formula (a + b)² = a² + 2ab + b². So the right side becomes 7² + 2*7*√(x² - 52) + (√(x² - 52))², which is 49 + 14√(x² - 52) + (x² - 52).\n\nSo putting it all together:\n\nx² + 165 = 49 + 14√(x² - 52) + x² - 52.\n\nHmm, let's simplify the right side. The x² terms will cancel out, right? Let's subtract x² from both sides:\n\n165 = 49 + 14√(x² - 52) - 52.\n\nSimplify the constants on the right:\n\n49 - 52 is -3, so:\n\n165 = -3 + 14√(x² - 52).\n\nNow, add 3 to both sides to isolate the radical term:\n\n165 + 3 = 14√(x² - 52).\n\nSo 168 = 14√(x² - 52).\n\nDivide both sides by 14:\n\n168 / 14 = √(x² - 52).\n\n12 = √(x² - 52).\n\nNow, square both sides again to eliminate the square root:\n\n12² = x² - 52.\n\n144 = x² - 52.\n\nAdd 52 to both sides:\n\n144 + 52 = x².\n\n196 = x².\n\nSo x = √196 = 14.\n\nBut wait, since the problem states that x is positive, we only take the positive root. So x = 14.\n\nBut hold on, when dealing with squaring equations, sometimes extraneous solutions can come up. I should check if this solution actually satisfies the original equation.\n\nLet's plug x = 14 back into the original equation:\n\n√(14² + 165) - √(14² - 52) = ?\n\nCalculate each term:\n\n14² is 196.\n\nSo first radical: √(196 + 165) = √361 = 19.\n\nSecond radical: √(196 - 52) = √144 = 12.\n\nSo 19 - 12 = 7, which is exactly the right-hand side. So yes, it checks out.\n\nTherefore, the only solution is x = 14. Since the problem says x is positive, we don't have to consider negative roots. So I think that's the answer.\nTo solve the equation \\(\\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\\) for positive \\(x\\), we proceed as follows:\n\n1. Start with the given equation:\n   \\[\n   \\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\n   \\]\n\n2. Isolate one of the square roots by moving \\(\\sqrt{x^2 - 52}\\) to the right side:\n   \\[\n   \\sqrt{x^2 + 165} = 7 + \\sqrt{x^2 - 52}\n   \\]\n\n3. Square both sides to eliminate the square root on the left:\n   \\[\n   (\\sqrt{x^2 + 165})^2 = (7 + \\sqrt{x^2 - 52})^2\n   \\]\n   Simplifying both sides, we get:\n   \\[\n   x^2 + 165 = 49 + 14\\sqrt{x^2 - 52} + (x^2 - 52)\n   \\]\n\n4. Combine like terms on the right side:\n   \\[\n   x^2 + 165 = x^2 - 52 + 49 + 14\\sqrt{x^2 - 52}\n   \\]\n   Simplifying further:\n   \\[\n   x^2 + 165 = x^2 - 3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n5. Subtract \\(x^2\\) from both sides:\n   \\[\n   165 = -3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n6. Add 3 to both sides to isolate the term with the square root:\n   \\[\n   168 = 14\\sqrt{x^2 - 52}\n   \\]\n\n7. Divide both sides by 14:\n   \\[\n   12 = \\sqrt{x^2 - 52}\n   \\]\n\n8. Square both sides again to eliminate the square root:\n   \\[\n   12^2 = x^2 - 52\n   \\]\n   Simplifying:\n   \\[\n   144 = x^2 - 52\n   \\]\n\n9. Add 52 to both sides to solve for \\(x^2\\):\n   \\[\n   196 = x^2\n   \\]\n\n10. Take the positive square root (since \\(x\\) is positive):\n    \\[\n    x = \\sqrt{196} = 14\n    \\]\n\n11. Verify the solution by substituting \\(x = 14\\) back into the original equation:\n    \\[\n    \\sqrt{14^2 + 165} - \\sqrt{14^2 - 52} = \\sqrt{196 + 165} - \\sqrt{196 - 52} = \\sqrt{361} - \\sqrt{144} = 19 - 12 = 7\n    \\]\n    The solution checks out.\n\nThus, the only positive solution is:\n\\[\n\\boxed{14}\n\\]</brain><answer>14</answer><|endoftext|>"

Let's truncate the pre fine-tuning dataset to `max_seq_length/2` since we don't want too long reasoning traces.

Note this might take 2 minutes!

In [10]:
dataset["N"] = dataset["Messages"].apply(lambda x: len(tokenizer.apply_chat_template(x)))

dataset = dataset.loc[dataset["N"] <= max_seq_length/2].copy()
dataset.shape

(63, 5)

We then tokenize the messages and convert it to a Hugging Face compatible dataset format:

In [11]:
from datasets import Dataset

dataset["text"] = tokenizer.apply_chat_template(dataset["Messages"].values.tolist(), tokenize = False)
dataset = Dataset.from_pandas(dataset)
dataset

Dataset({
    features: ['expected_answer', 'problem', 'generated_solution', 'Messages', 'N', 'text', '__index_level_0__'],
    num_rows: 63
})

Let's now pre fine-tune the model so it follows our custom GRPO formatting!

In [12]:
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 1, # Use GA to mimic batch size!
        warmup_steps = 5,
        num_train_epochs = 2, # Set this for 1 full training run.
        learning_rate = 2e-4, # Reduce to 2e-5 for long training runs
        logging_steps = 5,
        optim = "adamw_8bit",
        weight_decay = 0.001,
        lr_scheduler_type = "linear",
        seed = 3407,
        report_to = "none", # Use TrackIO/WandB etc
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/63 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

In [13]:
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 63 | Num Epochs = 2 | Total steps = 126
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 1 x 1) = 1
 "-____-"     Trainable parameters = 66,060,288 of 4,088,528,384 (1.62% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=126, training_loss=0.34615115643966765, metrics={'train_runtime': 216.5844, 'train_samples_per_second': 0.582, 'train_steps_per_second': 0.582, 'total_flos': 2522915879012352.0, 'train_loss': 0.34615115643966765, 'epoch': 2.0})

Let's check if the model has learnt to follow the custom format:

In [14]:
text = tokenizer.apply_chat_template(
    dataset[0]["Messages"][:2],
    tokenize = False,
    add_generation_prompt = True, # Must add for generation
)

from transformers import TextStreamer
_ = model.generate(
    **tokenizer(text, return_tensors = "pt").to("cuda"),
    temperature = 0,
    max_new_tokens = 1024,
    streamer = TextStreamer(tokenizer, skip_prompt = False),
)

You are given a problem.
Think about the problem and provide your working out.
Place it between <brain> and </brain>.
Then, provide your solution between <answer></answer><|endoftext|>Jenifer has 82 cents in pennies and nickels. Her younger brother mistook all her nickels for dimes and counted the total as $1.47. How many pennies does Jenifer have?<brain>Okay, let's see. So the problem is about Jenifer who has 82 cents in pennies and nickels. But her younger brother thought all the nickels were dimes and counted the total as $1.47. We need to find out how many pennies Jenifer has. Hmm, let me break this down.

First, I need to set up some equations. Let me denote the number of pennies as P and the number of nickels as N. Since pennies are worth 1 cent each and nickels 5 cents, the total value Jenifer has is 1*P + 5*N = 82 cents. That's the first equation.

Now, her brother mistook the nickels for dimes. Dimes are 10 cents each. So he counted the total as $1.47, which is 147 cents. So the equation for his count would be 1*P + 10*N = 147. Wait, but that's two equations now: one for the actual amount and one for the mistaken amount.

So the system of equations is:
1. P + 5N = 82
2. P + 10N = 147

I need to solve these two equations to find P. Let me subtract the first equation from the second to eliminate P. So (P + 10N) - (P + 5N) = 147 - 82. That simplifies to 5N = 65. Then N = 13. So there are 13 nickels.

Now plug N back into the first equation to find P. So P + 5*13 = 82. 5*13 is 65, so P = 82 - 65 = 17. So Jenifer has 17 pennies. Let me check that. 17 pennies are 17 cents, and 13 nickels are 65 cents. Total is 82 cents, which matches the problem statement. Then when the brother counts them as dimes, 13 dimes would be 130 cents, plus the 17 pennies, which is 147 cents. That also matches. So that seems right.

Wait, but let me make sure I didn't make a mistake. The equations were correct, and solving them gave N=13 and P=17. The checks worked out. So the answer should be 17 pennies. I think that's it.
To solve the problem, we need to determine how many pennies Jenifer has given the following information:

1. Jenifer has a total of 82 cents in pennies and nickels.
2. Her younger brother mistook all the nickels for dimes and counted the total as $1.47 (147 cents).

Let's denote:
- \( P \) as the number of pennies.
- \( N \) as the number of nickels.

We can set up the following system of equations based on the given information:

1. The total value of the coins is 82 cents:
   \[
   P + 5N = 82
   \]

2. The mistaken count, where nickels are treated as dimes, totals 147 cents:
   \[
   P + 10N = 147
   \]

To find the values of \( P \) and \( N \), we can solve this system of equations. First, we subtract the first equation from the second to eliminate \( P \):

\[
(P + 10N) - (P + 5N) = 147 - 82
\]

This simplifies to:

\[
5N = 65
\]

Solving for \( N \):

\[
N = \frac{65}{5} = 13
\]

Now that we have \( N = 13 \), we substitute this value back into the first equation to find \( P \):

\[
P + 5(13) = 82
\]

Simplifying:

\[
P + 65 = 82
\]

Solving for \( P \):

\[
P = 82 - 65 = 17
\]

Thus, Jenifer has \(\boxed{17}\) pennies.</brain><answer>17</answer><|endoftext|>

Yes it did follow the formatting! Great! Let's remove some items before the GRPO step

In [15]:
del dataset
torch.cuda.empty_cache()
import gc
gc.collect()

32

### Data Prep
<a name="Data"></a>

We're using Hugging Face's [Open R1 Math dataset](https://huggingface.co/datasets/open-r1/DAPO-Math-17k-Processed). You can also utilize OpenAI's famous [GSM8K dataset](https://huggingface.co/datasets/openai/gsm8k)

In [16]:
from datasets import load_dataset
dataset = load_dataset("open-r1/DAPO-Math-17k-Processed", "en", split = "train")
dataset

README.md: 0.00B [00:00, ?B/s]

en/train-00000-of-00001.parquet:   0%|          | 0.00/5.23M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/14116 [00:00<?, ? examples/s]

Dataset({
    features: ['prompt', 'solution', 'data_source', 'source_prompt', 'ability', 'reward_model', 'extra_info'],
    num_rows: 14116
})

Let's look at the first row:

In [20]:
from IPython.display import display,Markdown

In [22]:
dataset[5]["prompt"]

'For which $n$ is $n^4 + 6n^3 + 11n^2 + 3n + 31$ a perfect square?'

In [21]:
display(Markdown(dataset[5]["prompt"]))

For which $n$ is $n^4 + 6n^3 + 11n^2 + 3n + 31$ a perfect square?

In [23]:
dataset[0]["solution"]

'34'

In GSM8K, we notice all answers like about have a ####, so we extract it. But for the Open R1 dataset, we can skip the below.

In [24]:
def extract_hash_answer(text):
    # if "####" not in text: return None
    # return text.split("####")[1].strip()
    return text
extract_hash_answer(dataset[0]["solution"])

'34'

Let's map the dataset! and see the first row:

In [25]:
dataset = dataset.map(lambda x: {
    "prompt" : [
        {"role": "system", "content": system_prompt},
        {"role": "user",   "content": x["prompt"]},
    ],
    "answer": extract_hash_answer(x["solution"]),
})
dataset[0]

Map:   0%|          | 0/14116 [00:00<?, ? examples/s]

{'prompt': [{'content': 'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <brain> and </brain>.\nThen, provide your solution between <answer></answer>',
   'role': 'system'},
  {'content': 'In triangle $ABC$, $\\sin \\angle A = \\frac{4}{5}$ and $\\angle A < 90^\\circ$. Let $D$ be a point outside triangle $ABC$ such that $\\angle BAD = \\angle DAC$ and $\\angle BDC = 90^\\circ$. Suppose that $AD = 1$ and that $\\frac{BD}{CD} = \\frac{3}{2}$. If $AB + AC$ can be expressed in the form $\\frac{a\\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.',
   'role': 'user'}],
 'solution': '34',
 'data_source': 'math_dapo',
 'source_prompt': [{'content': 'Solve the following math problem step by step. The last line of your response should be of the form Answer: $Answer (without quotes) where $Answer is the answer to the problem.\n\nIn triangle $ABC$, $\\sin \\angle A = \\frac{4}{5}$ and $\\angle A < 90^\\circ$. Let $D$ be a point outside triangle $ABC$ such that $\\angle BAD = \\angle DAC$ and $\\angle BDC = 90^\\circ$. Suppose that $AD = 1$ and that $\\frac{BD}{CD} = \\frac{3}{2}$. If $AB + AC$ can be expressed in the form $\\frac{a\\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.\n\nRemember to put your answer on its own line after "Answer:".',
   'role': 'user'}],
 'ability': 'MATH',
 'reward_model': {'ground_truth': '34', 'style': 'rule-lighteval/MATH_v2'},
 'extra_info': {'index': '9a9b6eb4-a1cb-49d1-8c1e-62eaf2f74079'},
 'answer': '34'}

In [28]:
dataset[5]

{'prompt': [{'content': 'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <brain> and </brain>.\nThen, provide your solution between <answer></answer>',
   'role': 'system'},
  {'content': 'For which $n$ is $n^4 + 6n^3 + 11n^2 + 3n + 31$ a perfect square?',
   'role': 'user'}],
 'solution': '10',
 'data_source': 'math_dapo',
 'source_prompt': [{'content': 'Solve the following math problem step by step. The last line of your response should be of the form Answer: $Answer (without quotes) where $Answer is the answer to the problem.\n\nFor which $n$ is $n^4 + 6n^3 + 11n^2 + 3n + 31$ a perfect square?\n\nRemember to put your answer on its own line after "Answer:".',
   'role': 'user'}],
 'ability': 'MATH',
 'reward_model': {'ground_truth': '10', 'style': 'rule-lighteval/MATH_v2'},
 'extra_info': {'index': '96bd487f-c324-41b4-8015-f8234fe31bb4'},
 'answer': '10'}

We create a regex format to match the reasoning sections and answers:

In [31]:
import re

# Add optional EOS token matching
solution_end_regex = r"</answer>[\s]{0,}" + \
    "(?:" + re.escape(tokenizer.eos_token) + ")?"

match_format = re.compile(
    rf"{reasoning_end}.*?"\
    rf"{solution_start}(.+?){solution_end_regex}"\
    rf"[\s]{{0,}}$",
    flags = re.MULTILINE | re.DOTALL
)
match_format

re.compile(r'</brain>.*?<answer>(.+?)</answer>[\s]{0,}(?:<\|endoftext\|>)?[\s]{0,}$',
re.MULTILINE|re.DOTALL|re.UNICODE)

We verify it works:

In [32]:
match_format.findall(
    "Let me think!</brain>"\
    f"<answer>\n2\n</answer>",
)

['\n2\n']

In [33]:
match_format.findall(
    "<brain>Let me think!</brain>"\
    f"<answer>  2  </answer>\n\n",
)

['  2  ']

We now want to create a reward function to match the format exactly - we reward it with 3 points if it succeeds:

In [34]:
def match_format_exactly(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        # Match if format is seen exactly!
        if match_format.search(response) is not None: score += 3.0
        scores.append(score)
    return scores

If it fails, we want to reward the model if it at least follows the format partially, by counting each symbol:

In [35]:
def match_format_approximately(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        # Count how many keywords are seen - we penalize if too many!
        # If we see 1, then plus some points!

        # No need to reward <brain> since we always prepend it!
        # score += 0.5 if response.count(reasoning_start) == 1 else -1.0
        score += 0.5 if response.count(reasoning_end)   == 1 else -1.0
        score += 0.5 if response.count(solution_start)  == 1 else -1.0
        score += 0.5 if response.count(solution_end)    == 1 else -1.0
        scores.append(score)
    return scores

Finally, we want to extract the generated answer, and reward or penalize it! We also reward it based on how close the answer is to the true one via ratios:

In [36]:
def check_answer(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = [
        guess.group(1)
        if (guess := match_format.search(r)) is not None else None \
        for r in responses
    ]

    scores = []
    for guess, true_answer in zip(extracted_responses, answer):
        score = 0
        if guess is None:
            scores.append(-2.0)
            continue
        # Correct answer gets 5 points!
        if guess == true_answer:
            score += 5.0
        # Match if spaces are seen, but less reward
        elif guess.strip() == true_answer.strip():
            score += 3.5
        else:
            # We also reward it if the answer is close via ratios!
            # Ie if the answer is within some range, reward it!
            try:
                ratio = float(guess) / float(true_answer)
                if   ratio >= 0.9 and ratio <= 1.1: score += 2.0
                elif ratio >= 0.8 and ratio <= 1.2: score += 1.5
                else: score -= 2.5 # Penalize wrong answers
            except:
                score -= 4.5 # Penalize
        scores.append(score)
    return scores

Also sometimes it might not be 1 number as the answer, but like a sentence for example "The solution is $20" -> we extract 20.

We also remove possible commas for example as in 123,456

In [38]:
match_numbers = re.compile(
    solution_start + r".*?[\s]{0,}([-]?[\d\.\,]{1,})",
    flags = re.MULTILINE | re.DOTALL
)
print(match_numbers.findall("<answer>  0.34  </answer>"))
print(match_numbers.findall("<answer>  123,456  </answer>"))
print(match_numbers.findall("<answer>  -0.234  </answer>"))
print(match_numbers.findall("<answer>17</answer>"))

['0.34']
['123,456']
['-0.234']
['17']

We now prepare our main function which will print out the generated responses and the true answer, along with another reward function which converts text to float via `float` and sees if it's the same.

In [39]:
global PRINTED_TIMES
PRINTED_TIMES = 0
global PRINT_EVERY_STEPS
PRINT_EVERY_STEPS = 5

def check_numbers(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = [
        guess.group(1)
        if (guess := match_numbers.search(r)) is not None else None \
        for r in responses
    ]

    scores = []
    # Print only every few steps
    global PRINTED_TIMES
    global PRINT_EVERY_STEPS
    if PRINTED_TIMES % PRINT_EVERY_STEPS == 0:
        print(
            '*'*20 + f"Question:\n{question}", f"\nAnswer:\n{answer[0]}", f"\nResponse:\n{responses[0]}", f"\nExtracted:\n{extracted_responses[0]}"
        )
    PRINTED_TIMES += 1

    for guess, true_answer in zip(extracted_responses, answer):
        if guess is None:
            scores.append(-2.5)
            continue
        # Convert to numbers
        try:
            true_answer = float(true_answer.strip())
            # Remove commas like in 123,456
            guess       = float(guess.strip().replace(",", ""))
            scores.append(3.5 if guess == true_answer else -1.5)
        except:
            scores.append(0)
            continue
    return scores

Get the top 90% prompt length so we don't accidentally truncate them!

Ie we'll remove the top 10% long prompts.

In [40]:
tokenized = dataset.map(
    lambda x: {"tokens" : tokenizer.apply_chat_template(x["prompt"], add_generation_prompt = True, tokenize = True)},
    batched = True,
)
print(tokenizer.decode(tokenized[0]["tokens"]))
tokenized = tokenized.map(lambda x: {"L" : len(x["tokens"])})

import numpy as np
maximum_length = int(np.quantile(tokenized["L"], 0.9))
print("Max Length = ", maximum_length)

# Filter only samples smaller than 90% max length
dataset = dataset.select(np.where(np.array(tokenized["L"]) <= maximum_length)[0])
del tokenized

Map:   0%|          | 0/14116 [00:00<?, ? examples/s]

You are given a problem.
Think about the problem and provide your working out.
Place it between <brain> and </brain>.
Then, provide your solution between <answer></answer><|endoftext|>In triangle $ABC$, $\sin \angle A = \frac{4}{5}$ and $\angle A < 90^\circ$. Let $D$ be a point outside triangle $ABC$ such that $\angle BAD = \angle DAC$ and $\angle BDC = 90^\circ$. Suppose that $AD = 1$ and that $\frac{BD}{CD} = \frac{3}{2}$. If $AB + AC$ can be expressed in the form $\frac{a\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.<brain>

Map:   0%|          | 0/14116 [00:00<?, ? examples/s]

Max Length =  193

<a name="Train"></a>
### Train the model

Now set up GRPO Trainer and all configurations!

In [41]:
max_prompt_length = maximum_length + 1 # + 1 just in case!
max_completion_length = max_seq_length - max_prompt_length

from vllm import SamplingParams
vllm_sampling_params = SamplingParams(
    min_p = 0.1,
    top_p = 1.0,
    top_k = -1,
    seed = 3407,
    stop = [tokenizer.eos_token],
    include_stop_str_in_output = True,
)

from trl import GRPOConfig, GRPOTrainer
training_args = GRPOConfig(
    vllm_sampling_params = vllm_sampling_params,
    temperature = 1.0,
    learning_rate = 5e-6,
    weight_decay = 0.001,
    warmup_ratio = 0.1,
    lr_scheduler_type = "linear",
    optim = "adamw_8bit",
    logging_steps = 1,
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 1, # Increase to 4 for smoother training
    num_generations = 4, # Decrease if out of memory
    max_prompt_length = max_prompt_length,
    max_completion_length = max_completion_length,
    # num_train_epochs = 1, # Set to 1 for a full training run
    max_steps = 100,
    save_steps = 100,
    report_to = "none", # Can use Weights & Biases
    output_dir = "outputs",

    # For optional training + evaluation
    # fp16_full_eval = True,
    # per_device_eval_batch_size = 4,
    # eval_accumulation_steps = 1,
    # eval_strategy = "steps",
    # eval_steps = 1,
)

Unsloth: We now expect `per_device_train_batch_size` * `gradient_accumulation_steps` * `world_size` to be a multiple of `num_generations`.
We will change the batch size of 1 to the `num_generations` of 4

And let's run the trainer! If you scroll up, you'll see a table of rewards. The goal is to see the `reward` column increase!

You might have to wait 150 to 200 steps for any action. You'll probably get 0 reward for the first 100 steps. Please be patient!

| Step | Training Loss | reward    | reward_std | completion_length | kl       |
|------|---------------|-----------|------------|-------------------|----------|
| 1    | 0.000000      | 0.125000  | 0.000000   | 200.000000        | 0.000000 |
| 2    | 0.000000      | 0.072375  | 0.248112   | 200.000000        | 0.000000 |
| 3    | 0.000000      | -0.079000 | 0.163776   | 182.500000        | 0.000005 |

In [ ]:
# For optional training + evaluation
# new_dataset = dataset.train_test_split(test_size = 0.01)

trainer = GRPOTrainer(
    model = model,
    processing_class = tokenizer,
    reward_funcs = [
        match_format_exactly,
        match_format_approximately,
        check_answer,
        check_numbers,
    ],
    args = training_args,
    train_dataset = dataset,

    # For optional training + evaluation
    # train_dataset = new_dataset["train"],
    # eval_dataset = new_dataset["test"],
)
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 12,709 | Num Epochs = 1 | Total steps = 100
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 1 x 1) = 4
 "-____-"     Trainable parameters = 66,060,288 of 4,088,528,384 (1.62% trained)

Unsloth: Will smartly offload gradients to save VRAM!
********************Question:
Compute the number of positive integers that divide at least two of the integers in the set $\{1^1,2^2,3^3,4^4,5^5,6^6,7^7,8^8,9^9,10^{10}\}$.
Answer:
22
Response:
Okay, so I need to find the number of positive integers that divide at least two of the numbers in the set {1^1, 2^2, 3^3, ..., 10^10}. Hmm, let me think.

First, I should probably list out all the exponents here. Since each number in the set is of the form n^n, the exponents are from 1^1 up to 10^10. So the set is (1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000). Wait, so these are all these large numbers, like 10^10 is 10 billion. But I need to find divisors that are common to at least two of these numbers.

But how? Divisors that divide at least two numbers. So maybe I need to find common divisors. For example, if there's a number like 3 that divides both 27 (which is 3^3) and 6^6 (which is (2*3)^6 = 2^6 * 3^6), then 3 is a common divisor. So all common divisors of two numbers would be divisors of the greatest common divisor (GCD) of those two numbers.

Wait, so maybe I can organize this by finding the GCD of each pair and then the number of divisors of those GCDs? But there are 10 numbers in the set. The number of pairs is 10 choose 2, which is 45 pairs. For each pair, compute GCD and then count the divisors of that GCD. But that seems like a lot of work. Maybe there's a smarter way.

Alternatively, maybe think about the prime factorizations. Since the numbers are all of the form n^n, their prime factors are the primes in n raised to the power n. So the GCD of two numbers would be the minimum of the exponents for each prime. For example, GCD(9,729) where 9 is 3^2 and 729 is 3^6. The GCD is 3^2. Then the number of divisors is (2+1) = 3.

But I need divisors that divide at least two numbers. So maybe the total number of such divisors is the sum of the number of divisors of the GCDs of every pair. But computing that seems tedious. Maybe I can look for a pattern or a smarter approach.

Wait, maybe the problem is asking for the number of positive integers that divide at least two of the numbers in the set. So the total number of positive integers that are divisors of at least two of the numbers. So that's the union of all the sets of divisors of each pair.

Using the principle of inclusion-exclusion, the number of divisors of at least two numbers would be the sum of the sizes of each pair's gcd divisors minus the overlaps. But that still seems complicated. Maybe another way.

Alternatively, think about the numbers: 1, 4, 27, 256, 3125, 46656, 78125, 1000, 387420489, 10000000000. From these, which have common divisors? The obvious ones are numbers with common prime factors. Since 1 is not a prime and is 1^1, any divisor of 1 can't divide any of these other numbers except 1. So 1 is a common divisor of all pairs. So 1 is counted in every pair.

Then the problem reduces to finding the number of divisors that divide at least one other number besides 1. Because 1 is always a divisor of every number, so it's common to every pair. So if we consider all divisors of all pairs and then subtract the ones that divide only one number, we get the answer. Wait, no, the problem is asking for the number of positive integers that divide at least two of the integers in the set. So it's the union of the divisors of each pair. So we can use inclusion-exclusion.

But inclusion-exclusion for 45 pairs would be too much. Maybe there's a smarter way. Let me think differently. The number of divisors of a number n is σ₀(n). So the total number of divisors across all pairs is Σ(σ₀(gcd(a,b))) for all pairs (a,b). But counting this directly is hard. Maybe there's a formula or a pattern.

Wait, perhaps the problem is about counting the number of integers that are divisors of at least two elements in the set. So let's list the numbers: 1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000.

The divisors that are common to at least two numbers will be the divisors of the GCD of those two numbers. So maybe we can find the divisors of each pairwise GCD and then sum them up, but using inclusion-exclusion to avoid overcounting.

But since the numbers are 10 in the set, the number of pairs is 45. So we need to compute the number of divisors of the GCD of each pair. Then sum those numbers, subtract the intersections, add back triple intersections, etc. That's quite involved. Maybe there's a trick.

Wait, perhaps the answer is related to the number of integers that have two or more distinct prime factors, since those could be divisors of multiple numbers. For example, 6 divides both 4 and 6 in some cases, but in this set, numbers like 6 would be divisors of 6^6, but 4 is 2^2. So perhaps primes factors overlap. But 10^10 has all primes up to 10. Wait, no, not necessarily. 10^10 is 2^10 * 5^10. So the exponents vary for each number.

Alternatively, maybe the answer is the number of divisors of the elements that share at least one common prime factor in their exponents. Wait, that might help. For example, if two numbers share a prime, their GCD will have that prime.

Let me try to think about the prime factorizations. Each number is n^n, so the exponents of primes in their factorization are the primes dividing n, each raised to the power n. For example, 256 is 2^8, 3125 is 5^5, 46656 is 2^6 * 3^6, 823543 is 7^7, etc.

The GCD of two numbers a and b is the product of the minimum exponents of common primes. So for example, GCD of 10^10 and 8^8: 10^10 = 2^10 * 5^10, 8^8 = 2^24. So GCD is 2^8. Then number of divisors is 9.

Similarly, GCD of 27 and 6^6: 27 is 3^3, 6^6 = 2^6 * 3^6. So GCD is 3^3, number of divisors 4.

So the number of divisors for each pair's GCD contributes to the total count. But since each divisor appears in pairs, maybe the total number is the sum of the divisors of each GCD, divided by 2? But wait, that's not correct. For example, consider two pairs with GCDs 2 and 3. The divisors 1 and 2 are shared by both pairs. So inclusion-exclusion is needed here.

So the total number is Σ[divisors of gcd(a,b)] - Σ[divisors counted in more than one pair], but this involves triple intersections, etc. Which in this case might be too complicated.

Alternatively, maybe the answer is the number of distinct divisors across all pairs. For example, something like the total number of divisors for all numbers, minus the number of divisors that
Extracted:
None

********************Question:
The sum of $\lfloor x \rfloor$ for all real numbers $x$ satisfying the equation $16 + 15x + 15x^2 = \lfloor x \rfloor^3$ is:
Answer:
33
Response:
Okay, let's see. I need to find all real numbers x such that 16 + 15x + 15x² equals the floor of x cubed, and then sum all those floor values. Hmm, floor function, quadratic equation, and a cubic one. Maybe I can find the range of x where this equation holds?

First, let me recall that the floor function, ⌊x⌋, gives the greatest integer less than or equal to x. So, if I let n = ⌊x⌋, then n is an integer, and n ≤ x < n+1. The equation becomes 16 + 15x + 15x² = n³.

Let me rearrange the equation to standard quadratic form: 15x² + 15x + 16 - n³ = 0. So, it's a quadratic in x. The solutions to this would be between n and n+1 because of the floor condition.

The quadratic equation is 15x² + 15x + (16 - n³) = 0. The discriminant D = b² - 4ac = 225 - 4*15*(16 - n³) = 225 - 60(16 - n³) = 225 - 960 + 60n³ = -735 + 60n³.

For real solutions, D must be non-negative: -735 + 60n³ ≥ 0 ⇒ 60n³ ≥ 735 ⇒ n³ ≥ 735/60 = 12.25. So n³ is at least 12.25, which means n is at least 3 since 3³=27, which is greater than 12.25. Let me check n=2: 2³=8, which is less than 12.25. So n must be 3 or higher.

Wait, but when n=3, n³=27. Let's plug n=3 into the quadratic equation: 15x² + 15x + (16 - 27) = 15x² + 15x -11 = 0. The discriminant is 225 - 4*15*(-11) = 225 +660 = 885. So x has real solutions. Let me solve this. The quadratic formula: x = [-15 ±√885]/30. Since x has to be between 3 and 4 (since n=3), we take the positive root here. So x ≈ (15 + √885)/30. Let's approximate √885. 30²=900, so √885 is slightly less than 30. 885/30=29.5, so √885 is around 29.75. Then x ≈ (15 + 29.75)/30 ≈ 44.75/30 ≈ 1.4917. But wait, n is 3 here, so x should be around 3. This is conflicting. Hmm, maybe I made a mistake.

Wait, the equation is 16 + 15x + 15x² = n³, which is 15x² + 15x + (16 - n³) = 0. If n=3, then 15x² + 15x -11 = 0. Solutions are ( -15 ± √885 ) / 30. Since the coefficient of x² is positive, the parabola opens upwards. The solutions are the roots between the vertex. The vertex is at x = -b/(2a) = -15/(30) = -0.5. So both roots are less than 3. Thus, the solution for x is not between 3 and 4. So n cannot be 3. So either there's no solution, or maybe I underestimated n.

Wait, the condition is that the solutions must be in [n, n+1). But since the roots are less than 3, and n=3, the equation doesn't have solutions in [3,4). So perhaps n must be less than 3. Let me check n=2. Then n³=8. The equation becomes 15x² + 15x +16 -8 = 0 ⇒ 15x² +15x +8=0. The discriminant is 225 - 480 = -255, which is negative. So no real solutions for n=2.

What about n=1? n³=1. Equation: 15x² +15x +16-1=0 ⇒ 15x² +15x +15=0. Dividing by 15: x² +x +1=0. Discriminant is 1-4= -3. No real solutions.

n=0: 0³=0. Equation: 15x² +15x +16=0. Discriminant is 225-960=-735. No real solutions.

n=-1: (-1)³=-1. Equation: 15x² +15x +17=0. Discriminant 225-1020=-795. No real solutions.

n=-2: -8. Equation: 15x² +15x +24=0. Discriminant 225-1440=-1215. No real solutions.

So for n≥3, we have real solutions, but the roots weren't in [3,4). For n<3, no real solutions. So perhaps the only possible n is 3, but the roots weren't within 3≤ x <4. So maybe there's no solution? Wait, but the problem says "all real numbers x" satisfying the equation. So maybe there are no solutions, hence the sum is 0. But let me double-check.

Wait, maybe I miscalculated the roots. For n=3, the quadratic is 15x² +15x -11=0. The positive root is ( -15 + √885 ) /30. √885 is approximately 29.75, so ( -15+29.75 ) /30 = 14.75/30 ≈ 0.4917. But n=3, so x needs to be ≥3. Since the root is approximately 0.4917, which is less than 3, the quadratic equation doesn't have solutions in [3,4). Thus, no x satisfies the equation for n=3. Therefore, there are no real solutions. Hence, the sum of floor values is 0.

Wait, but the problem might have a mistake, or maybe I missed something. let me verify the equation again. The original equation is 16 +15x +15x² = ⌊x⌋³. Let me check if there's any x where this holds. Maybe near integer values? Let's try x=3. Then left side: 16 +45 +135 = 196. Right side: 3³=27. 196 ≠ 27.

x=2: 16 +30 +60=106 ≠8.

x=4: 16 +60 +240=316 ≠64.

x=5: 16 +75 +375=466 ≠125.

So as x increases, the left side grows faster than the cube. Similarly, for x<3. For example, x=1.5: 16 +22.5 +15*(2.25)=16+22.5+33.75=72.25. ⌊1.5⌋=1, 1³=1. 72.25≠1.

x=2.5: 16 +37.5 +61.875= ~115.375. ⌊2.5⌋=2, 8. 11
Extracted:
None
********************Question:
Letters $A, B, C,$ and $D$ represent four different digits from 0, 1, 2, 3, ..., 9. If $\frac{A+B}{C+D}$ is an integer that is as large as possible, what is the value of $A+B$?
Answer:
17
Response:
Okay, so I need to find four different digits A, B, C, and D (from 0 to 9) such that when I add A and B, divide by C and D, the result is the largest possible integer. Ultimately, I need to find the value of A+B. Hmm, let me break this down.

First, the expression is (A + B)/(C + D) needs to be an integer. That means C + D must be a divisor of A + B. Since we want the largest possible integer result, to maximize (A + B)/(C + D), we need to maximize A + B relative to C + D. So, the denominator C + D should be as small as possible, because dividing by a smaller number will give a larger result. Wait, but C and D are different digits, right? So the smallest possible sum for C + D is 0 + 1 = 1. But if C or D is 0, then the denominator is 1, which would make (A + B)/1 = A + B. So, if C and D are 0 and 1, then A + B can be as large as possible since we're dividing by 1. But all digits are different, so if we pick C=0 and D=1, then A and B can be any of the remaining digits, but we need them to be different too. To maximize A+B, we should pick the two largest possible digits for A and B, which would be 8 and 9. So A+B would be 17. Let me check if that works.

If C=0 and D=1, then C+D=1. Then A+B divided by 1 is just A+B. So A+B can be 17 (e.g., A=8, B=9). For other choices of C and D, like C=2, D=1, then C+D=3. Then A+B must be a multiple of 3. The maximum possible A+B in this case would be 18 (with 9 and 9, but they have to be different). But since digits have to be different, A+B can't be 18. So 17 is achievable with 8 and 9. If C and D were 1 and 2, sum 3, then max A+B is 18, but digits have to be different, so 9 and 9 is not allowed. So no larger than 17. So maybe 17 is the maximum.

Alternatively, maybe there's a combination where C+D is greater than 1, but A+B is a larger multiple. For example, if C+D=2, then A+B must be even. The maximum even sum with different digits is 18 (9+8), but then we need C+D=2. The smallest pair is 0 and 1. But if we use 0 and 1, then A+B is 18, which is larger than 17. Let me check that. If C=0, D=1, then A+B=18. So that's larger. So maybe the answer is 18. Wait, but earlier thought was 17. Let me verify.

If A=9, B=8, C=0, D=1, then (9+8)/(0+1) = 17/1 =17. But if A=9, B=8, C=1, D=0, then (9+8)/(1+0) =17/1=17. Same. So both 17 and 18 are possible? Wait, no. Wait, if A=9, B=8, C=0, D=1, then A+B=17. If I set C+D=2, like C=0, D=2, then A+B must be a multiple of 2. Maximum A+B with different digits is 18, achieved by 9 and 9, but they have to be different. So 18 is possible. So 18 is larger. So the answer is 18.

But wait, let me check if 18 is achievable. If C=0 and D=2, then C+D=2. Then A+B must be a multiple of 2. The maximum A+B is 18 (9 and 9, but they have to be different). So 8 and 10? 8 and 10 are digits, no. Wait, digits are from 0 to 9. So 9 and 9 is not allowed. So the maximum is subtracting the smallest, which is 8 and 10 not possible. So the maximum A+B is 8+9=17. But when C+D=2, A+B must be even. The maximum even sum is 8+6=14, 7+5=12, 6+4=10, 5+3=8, 4+2=6, 3+1=4, 2+0=2. So the largest is 14. But wait, but when C+D=3, like C=1, D=2, then A+B must be multiple of 3. The maximum is 16 (8,8 not allowed) so 9,7=16, 8,6=14, 7,5=12, etc. So the maximum higher than 14 is 16. So 16 is possible with C+D=3. So 16. But 18 is not possible with C+D=2. So the maximum is 16. Even though C=0, D=2 gives A+B=16 (9,7). So 16 is the largest.

Wait, so maybe the answer is 16. Let me verify.

If C=1, D=2, then C+D=3. Then A+B must be a multiple of 3. The largest sum with different digits is 8+9=17, but 17 divided by 3 is not an integer. So 8+8=16, which is divisible by 3. So A=8, B=8, C=1, D=2. But digits have to be different, right? So 8 and 8 are the same. So the next lower is 7+9=16, which is divisible by 3. So 7+9=16. Then C+D=3, so C and D are 1 and 2. So A=7, B=9, C=1, D=2. Then (7+9)/(1+2)=16/3, which is not an integer. Wait, that's not an integer. So that's invalid. Next is 6+10=16, but 10 is not a digit. So digits from 0-9. So the maximum is 8+8=16, but digits must be different. So 7+9=16. Then divide by 3. But 16/3 is not an integer. So that's invalid. So the next is 5+11=16, no. So 4+12=16, no. So 3+13=16, no. 2+14=16, no. 1+15=16, no. 0+16=16, no. Wait, none of these add up to 16 with different digits. So the maximum A+B that's a multiple of 3 is 15 (7+8), which divided by 3 gives 5. So 7+8=15, then C+D=3. So digits can be 1,2 or 0,3, etc. But we need to maximize A+B. Let's take the largest possible digits for A and B. So 8 and 7 give 15. Then C+D=3. So the digits can be 1,2 or 0,3. So A=8, B=7, C=1, D=2. Then (8+7)/(1+2) =15/3=5. That works. So 15 is a possible sum. But earlier thought was 16 was possible, but that didn't work. So 15 is achievable. So the maximum then is 15.

Wait, but let's check if there's a higher multiple. The multiples of 3 higher than 15 with different digits
Extracted:
None

<a name="Inference"></a>
### Inference
Now let's try the model we just trained! First, let's first try the model without any GRPO trained:

In [ ]:
text = "What is the sqrt of 101?"

from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 1024,
)
output = model.fast_generate(
    [text],
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

' - Answers\nEducation\nMath and Arithmetic\nWhat is the sqrt of 101?\nWiki User\n∙ 2009-06-05 01:02:40\nBest Answer\nCopy\n10.05\nWiki User\n∙ 2009-06-05 01:02:40\nThis answer is:\n🙏\n0\n🤨\n0\n😮\n0\nWhat is the sqrt of 100?\nThe square root of 100 is 10; 10x10=100\nWhat is the Sqrt of 100?\nSqrt (100) = +10 &amp; -10 since both (+10) X (+10) and (-10) X (-\n10) equal 100\nWhat is the sqrt of 10000?\nIt is 100.\nHow many meters in a kilometer?\nThere are 1000 meters in a kilometer. 100 centimeter in a\nmeter. 1,000 meters in a km. 100cm in a meter.\nThe square root 100 is?\n-10 +10\nSqrt x equals 7 sqrt 2 find the value of x?\nSqrt(x) = 7 Sqrt(2) x = 72 x 2 x = 49 x 2 x = 98\nSqrt 100 simplified?\nSqrt(100) = 10 is its simplest form.\nWhat is the sqr root of 100?\n10 or -10 because 10*10=100\nand (-10)(-10)=100\nSqr\'s and cubs?\nSqrt(100) = 10 and 102 = 100Sqrt(1000) = 31.6 and 31.62 = 10001Sqrt(24) = 4.9 and 4.92 = 24If you are unsure, just check them out by calculator.The "cube" of a number x means x multiplied by itself, twice: x x x or x cubed x3\nHow do you find the square root of 100?\n10\nWhat is the square root of 100 in radical form?\nThe square root of 100 is 10.That is already in radical form.\nHow many m in 100 km?\nThere are a thousand (1,000) metres in one (1) kilometre: 1 kilometre = 1,000 metres.There are a thousand (1,000) metres in one (1) kilometre: 1 kilometre = 1,000 metres.There are a thousand (1,000) metres in one (1) kilometre: 1 kilometre = 1,000 metres.There are a thousand (1,000) metres in one (1) kilometre: 1 kilometre = 1,000 metres.\nWhat is 1 sqrt called?\nThe square root of 1 is 1.\nthe square root of 1 is 1, because 1&sup2; = 1.\nWhat is 2 sqrt 10 x 2 sqrt 10?\n40\nCan you help me with math i am having problems with sqrt 102 divided by sqrt 45?\nNo.\nWhat is Sqrt 100?\nThe square root of 100 is 10. :)\nWhat does sqrt of 100 squared mean?\n100\nDoes sqrt 9 over 5 times 10 over sqrt 3 equal 3sqrt 30 over 5?\nno.\nWhat is the sqrt of 23?\n2 sqrt 5 8 1/3 and 13 17/30\nWhat is 5 sqrt 10 x 5 sqrt 10?\n25 sqrt 100\nWhat is the exact sqrt of 2 and what is the sqrt of 2?\nsqrt2 and 1.414\nWhat is the radicand if sqrt 101 is the radical and sqrt 101 is written in simple radical form?\n101\nWhat is the answer to sqrt 100?\n10\nWhat is a square root of 100?\nThe square root of 100 is 10.\n10 squared equals 100. The square root of 100 is 10.\nSqrt 54?\nThe square root of 54'

And now with the LoRA we just trained with GRPO - we first save the LoRA first!

In [ ]:
model.save_lora("grpo_saved_lora")

Verify LoRA is actually trained!

In [ ]:
from safetensors import safe_open

tensors = {}
with safe_open("grpo_saved_lora/adapter_model.safetensors", framework = "pt") as f:
    # Verify both A and B are non zero
    for key in f.keys():
        tensor = f.get_tensor(key)
        n_zeros = (tensor == 0).sum() / tensor.numel()
        assert(n_zeros.item() != tensor.numel())

Now we load the LoRA and test:

In [ ]:
messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user",   "content": "What is the sqrt of 101?"},
]

text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
    tokenize = False,
)
from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 2048,
)
output = model.fast_generate(
    text,
    sampling_params = sampling_params,
    lora_request = model.load_lora("grpo_saved_lora"),
)[0].outputs[0].text

output

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

"Okay, so I need to find the square root of 101. Hmm, let me think. I remember that square roots of numbers between perfect squares are irrational, meaning they can't be expressed as simple fractions. Let's see, the perfect squares around 101 are 100 and 121. Since 10² is 100 and 11² is 121, the square root of 101 must be between 10 and 11. \n\nWait, but how close is it to 10 or 11? Maybe I can estimate it a bit more. Let me try multiplying 10.05 by itself. Calculating (10.05)² would be 10.05 * 10.05. Let's break that down: 10 * 10 = 100, 10*0.05=0.5, 0.05*10=0.5, and 0.05*0.05=0.0025. Adding those up: 100 + 0.5 + 0.5 + 0.0025 = 101.0025. That's a bit more than 101. So maybe 10.05 is too high. \n\nLet me try 10.04... Let's compute (10.04)². That would be 10.04 * 10.04. Breaking it down: 100 + 40*0.04=1.6 + 0.04*0.04=0.0016. So 100 + 1.6 + 0.0016 = 101.6016. Still a bit high. So maybe 10.03. Let's try (10.03)²: 100 + 30*0.03=0.9 + 0.03*0.03=0.0009. Adding gives 100 + 0.9 + 0.0009 = 100.9009. That's less than 101. So the square root has to be between 10.03 and 10.04. \n\nLet me try 10.035. Then (10.035)²: 100 + 35*0.03=1.05 + 0.035*0.035. Wait, 0.035*0.035 is 0.001225. So total: 100 + 1.05 + 0.001225 = 101.051225. That's slightly more than 101. So now it's between 10.03 and 10.035. \n\nLet me try 10.032. Then (10.032)^2: 100 + 64*0.03=1.92 + 0.032*0.032=0.001024. So total: 100 + 1.92 + 0.001024 = 101.921024. Wait, that's higher. So 10.032 is too high. So the square root is between 10.03 and 10.032. And we need more precision. \n\nHmm, but calculators are available nowadays, right? But since I'm doing this manually, I can estimate. So the square root of 101 is approximately 10.049875. But since the problem likely expects a simplified radical form, which is √101, since it's not a perfect square. But if a decimal is preferred, then closer to 10.04987.\nTo find the square root of 101, we note that it lies between the perfect squares 100 and 121, whose square roots are 10 and 11, respectively. Therefore, \\(\\sqrt{101}\\) must be between 10 and 11.\n\nTo refine the approximation, we can use the method of successive approximation. Let's start by testing values around the midpoint between 10 and 11.\n\n1. Calculate \\(10.06^2\\):\n   \\[\n   10.06 \\times 10.06 = 101.2036\n   \\]\n   This is slightly higher than 101.\n\n2. Calculate \\(10.05^2\\):\n   \\[\n   10.05 \\times 10.05 = 101.0025\n   \\]\n   This is slightly higher than 101 but closer.\n\n3. Calculate \\(10.04^2\\):\n   \\[\n   10.04 \\times 10.04 = 100.8016\n   \\]\n   This is slightly lower than 101.\n\nSince \\(10.05^2 = 101.0025\\) is slightly above 101 and \\(10.04^2 = 100.8016\\) is slightly below 101, the square root of 101 must be between 10.04 and 10.05. To get a more precise value, we can try a value between these two, such as 10.049.\n\n4. Calculate \\(10.049^2\\):\n   \\[\n   10.049 \\times 10.049 = 100.980401\n   \\]\n   This is very close but still slightly below 101.\n\n5. Calculate \\(10.0498^2\\):\n   \\[\n   10.0498 \\times 10.0498 = 100.99804004\n   \\]\n   This is still a bit below 101.\n\n6. Calculate \\(10.04987^2\\):\n   \\[\n   10.04987 \\times 10.04987 = 101.00000009\n   \\]\n   This is very close to 101.\n\nThus, the square root of 101 is approximately \\(10.0499875\\).\n\nHowever, since the problem does not specify the level of precision required, the most precise value we can provide is:\n\n\\[\n\\boxed{10.049875}\n\\]<end_working_out><SOLUTION>10.049875</SOLUTION>"

Our reasoning model is much better - it's not always correct, since we only trained it for an hour or so - it'll be better if we extend the sequence length and train for longer!

<a name="Save"></a>
### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens. See [our docs](https://unsloth.ai/docs/basics/inference-and-deployment) for more deployment options.

In [ ]:
# Merge to 16bit
if False: model.save_pretrained_merged("qwen_finetune_16bit", tokenizer, save_method = "merged_16bit",)
if False: model.push_to_hub_merged("HF_USERNAME/qwen_finetune_16bit", tokenizer, save_method = "merged_16bit", token = "YOUR_HF_TOKEN")

# Merge to 4bit
if False: model.save_pretrained_merged("qwen_finetune_4bit", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("HF_USERNAME/qwen_finetune_4bit", tokenizer, save_method = "merged_4bit", token = "YOUR_HF_TOKEN")

# Just LoRA adapters
if False:
    model.save_pretrained("qwen_lora")
    tokenizer.save_pretrained("qwen_lora")
if False:
    model.push_to_hub("HF_USERNAME/qwen_lora", token = "YOUR_HF_TOKEN")
    tokenizer.push_to_hub("HF_USERNAME/qwen_lora", token = "YOUR_HF_TOKEN")

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [docs page](https://unsloth.ai/docs/basics/inference-and-deployment/saving-to-gguf)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

[**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)

In [ ]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("qwen_finetune", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False: model.push_to_hub_gguf("HF_USERNAME/qwen_finetune", tokenizer, token = "YOUR_HF_TOKEN")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("qwen_finetune", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("HF_USERNAME/qwen_finetune", tokenizer, quantization_method = "f16", token = "YOUR_HF_TOKEN")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("qwen_finetune", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("HF_USERNAME/qwen_finetune", tokenizer, quantization_method = "q4_k_m", token = "YOUR_HF_TOKEN")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "HF_USERNAME/qwen_finetune", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "YOUR_HF_TOKEN",
    )

Now, use the `qwen_finetune.Q8_0.gguf` file or `qwen_finetune.Q4_K_M.gguf` file in llama.cpp.

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other resources:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
4. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://unsloth.ai/docs/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>

  This notebook and all Unsloth notebooks are licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).